<ix>
<message date="1/1/1998" time="">
 Sections will report the elapsed time (E), the minimum and maximum CPU time (C [min,max]), the minimum, maximum and total memory usage (M [min,max,total]) and the minimum, maximum and total peak memory usage during the simulation (P [min,max,total]) across all processes.
</message>
<message date="1/1/1998" time="">
 Loading extension: custom_scripts
</message>
<message date="1/1/1998" time="">
 Use of property aliases is enabled. There are 1097 such aliases which can be used in place of fully qualified property identifiers. Refer to Appendix &apos;Property identifiers&apos; in the Intersect User Guide for details.
</message>
<message date="1/1/1998" time="">
 Checking for licenses.
</message>
<message date="1/1/1998" time="">
 Successfully checked out 1 license of feature ix_fm.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_RESERVOIR_DEFINITION.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_FLUIDS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_ROCKS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_REGIONS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_SEPARATORS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_WELLS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_WELL_CONNECTIONS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_RESERVOIR_SIMULATION_SETTINGS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_PROPERTY_EDITS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;SNARK_FM_RES_IX_EDIT.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_WELL_COMPLETIONS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_HM_FM.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_FM_INIT.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Running simulation using: &apos;HM_REPORT_SETTINGS.ixf&apos;.
</message>
<message date="1/1/1998" time="">
 Field Management FluidSystem FluidType is set to BLACKOIL
</message>
<warning date="1/1/1998" time="">
 Edit property &apos;PERMEABILITY_MULTIPLIER_COMPACTION&apos; is not valid for node BoxPropertyEdit. It will be removed.
</warning>
<message date="1/1/1998" time="">
 FluidSystem can be omitted in a single reservoir simulation.
</message>
<message date="1/1/1998" time="">
 3D reports output have been activated.
</message>
<warning date="1/1/1998" time="">
 Separator &apos;Standard_Conditions&apos; will have no effect as the fluid model is black-oil
</warning>
<warning date="1/1/1998" time="">
 OilSurfaceDensity value defined in oil table &apos;OilTable1&apos; will be ignored. It is only used if Variable API is present.
</warning>
<warning date="1/1/1998" time="">
 The maximum saturated pressure for the oil PVT (= 3300 psi) is different from the maximum pressure for the gas PVT (= 3400 psi).
</warning>
<warning date="1/1/1998" time="">
 The saturated oil density is not decreasing with increasing bubble point pressure. Please review the OilTable FormationVolumeFactor data. (Set VerbosityLevel to 2 in FluidMgr for more information.)
</warning>
<message date="1/1/1998" time="">
 Running the default workflow (grids processed in Intersect).
</message>
<message date="1/1/1998" time="">
 Performing internal adjacency calculation for grid CoarseGrid.
</message>
<message date="1/1/1998" time="">
 Processing bulk data fault definitions
</message>
<message date="1/1/1998" time="">
 Bulk data fault &apos;Fault 1&apos; has 390 connections
</message>
<message date="1/1/1998" time="">
 Bulk data fault &apos;Fault 2&apos; has 675 connections
</message>
<message date="1/1/1998" time="">
 Bulk data fault &apos;Fault 3&apos; has 283 connections
</message>
<message date="1/1/1998" time="">
 3 faults, defined in bulk data, have been loaded.
</message>
<message date="1/1/1998" time="">
 Identifying connections assigned to faults.
</message>
<message date="1/1/1998" time="">
 Loaded region family &apos;PVT_REGION&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded region family &apos;EQUILIBRATION_REGION&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded region family &apos;ROCK_COMPACTION_REGION&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded region family &apos;SATURATION_FUNCTION_DRAINAGE_TABLE_NO&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded grid property &apos;PERM_I&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded grid property &apos;PERM_J&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded grid property &apos;PERM_K&apos;.
</message>
<message date="1/1/1998" time="">
 Loaded grid property &apos;POROSITY&apos;.
</message>
<message date="1/1/1998" time="">
 Cell volume not provided as a cell property. Calculating from geometry.
</message>
<message date="1/1/1998" time="">
 Cell center coordinate not provided as a cell property for 3 axis directions. Recalculating all cell center coordinates from geometry.
</message>
<message date="1/1/1998" time="">
 Using depth calc method: top_depth = min(top), bottom_depth = max(bottom)
</message>
<message date="1/1/1998" time="">
 Pore volume not provided as a cell property. Calculating from cell volume and porosity.
</message>
<warning date="1/1/1998" time="">
 There were 1585 cell(s) with negative or undefined porosity. The porosity for the cell(s) will be reset to zero.
</warning>
<message date="1/1/1998" time="">
 0 cells (of 6768) have been marked as inactive due to ACTNUM, host or missing geometry filtering.
</message>
<message date="1/1/1998" time="">
 1585 cells (of 6768) have been marked as inactive due to Min Pore Volume filtering. 0 additional cells which fall below the filter threshold were already inactive.
</message>
<message date="1/1/1998" time="">
 Calculating transmissibilities.
</message>
<message date="1/1/1998" time="">
 Pinchouts will not be created across LGR boundaries.
</message>
<message date="1/1/1998" time="">
 Processing minimum pore volume thresholds for a second time.
</message>
<message date="1/1/1998" time="">
 4628 neighbor connections and 0 non-neighbor connections have been removed due to one (or both) of the cells being inactive.
</message>
<message date="1/1/1998" time="">
 Performing parallel partitioning.
</message>
<message date="1/1/1998" time="">
 Reordering local cells by global cell ID.
</message>
<message date="1/1/1998" time="">
 There are 475 non neighbor connections which will be inlined for the purposes of Initial 3D transmissibility reporting.
</message>
<message date="1/1/1998" time="">
 Validating node &apos;Equilibrium[&apos;EQLNUM_1_PVTNUM_1&apos;]&apos; created from node &apos;Equilibrium[&apos;PVTNUM_1&apos;]&apos;.
</message>
<message date="1/1/1998" time="">
 Rock models will be associated with reservoir cells using the RegionFamily ROCKMODEL_REGION.
</message>
<message date="1/1/1998" time="">
 Fluid models will be associated with reservoir cells using the RegionFamily FLUIDMODEL_REGION.
</message>
<message date="1/1/1998" time="">
 Equilibration models will be associated with reservoir cells using the RegionFamily EQUILMODEL_REGION.
</message>
<message date="1/1/1998" time="">
 Successfully loaded the grid.
</message>
<message date="1/1/1998" time="">
 Equilibrium fluid type for &apos;EQLNUM_1_PVTNUM_1&apos; is not set. It will be recalculated.
</message>
<message date="1/1/1998" time="">
 Equilibration fluid type for &apos;EQLNUM_1_PVTNUM_1&apos; with top=7552.66 ft, bottom=9017.77 ft, datum=7000 ft, goc=7000 ft, woc=8200 ft is set to &apos;BUBBLE_POINT&apos;.
</message>
<message date="1/1/1998" time="">
 Equilibration mode based on mobile phases in reservoir=WO, gas=DRY, rsvd/pbvd=YES, rvvd/pdvd=NO, datum_vs_goc=EQUAL.
</message>
<message date="1/1/1998" time="">
 Setting unspecified temperature for equilibrium model &apos;EQLNUM_1_PVTNUM_1&apos; to standard conditions (60 degF).
</message>
<warning date="1/1/1998" time="">
 The gas oil contact depth (7000.000 ft) for the equilibrium model &apos;EQLNUM_1_PVTNUM_1&apos; is not within the range of cell depths. Cell depths for this model range from 7552.661 ft to 9017.771 ft.
</warning>
<warning date="1/1/1998" time="">
 The datum depth (7000.000 ft) for the equilibrium model &apos;EQLNUM_1_PVTNUM_1&apos; is not within the range of cell depths. Cells associated with this model extend from 7552.661 ft to 9017.771 ft.
</warning>
<message date="1/1/1998" time="">
 The oil gas transition adjustment will not be applied to the equilibrium model &apos;EQLNUM_1_PVTNUM_1&apos; since the GOC is not within the reservoir.
</message>
<warning date="1/1/1998" time="">
 The equilibrium model &apos;EQLNUM_1_PVTNUM_1&apos; is not thermodynamically consistent since the oil phase pressure at the GOC equals 3035.7 psi whilst the bubble point pressure at the GOC equals 1062.2 psi.
</warning>
<message date="1/1/1998" time="">
 3D reports output have been activated.
</message>
<message date="1/1/1998" time="">
 Checking for licenses.
</message>
<message date="1/1/1998" time="">
 Successfully checked out 1 license of feature ix_base.
</message>
<message date="1/1/1998" time="">
 Simulation will run without solving nonlinear systems since SimulationLevel field in Simulation node was set to SKIP_TIMESTEP.
</message>
<message date="1/1/1998" time="">
 Total number of time steps = 0, nonlinear iterations = 0, linear iterations = 0 

</message>
<message date="1/1/1998" time="">
 The OBSH file in the AFI file (HM.obsh) has been set as DataFileName on HistoricalDataControl:New Historical Data Control 1.
</message>
<message date="1/1/1998" time="">
 3D reports output have been activated.
</message>
<warning date="1/1/1998" time="">
 OilSurfaceDensity value defined in oil table &apos;OilTable1&apos; will be ignored. It is only used if Variable API is present.
</warning>
<warning date="1/1/1998" time="">
 The maximum saturated pressure for the oil PVT (= 3300 psi) is different from the maximum pressure for the gas PVT (= 3400 psi).
</warning>
<warning date="1/1/1998" time="">
 The saturated oil density is not decreasing with increasing bubble point pressure. Please review the OilTable FormationVolumeFactor data. (Set VerbosityLevel to 2 in FluidMgr for more information.)
</warning>
<message date="1/1/1998" time="">
 Well &apos;PROD1&apos; has been assigned fluid model &apos;PVTNUM_1&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD2&apos; has been assigned fluid model &apos;PVTNUM_1&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD3&apos; has been assigned fluid model &apos;PVTNUM_1&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD4&apos; has been assigned fluid model &apos;PVTNUM_1&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PRODUCER&apos; has been assigned fluid model &apos;PVTNUM_1&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD1&apos; has been assigned separator &apos;Default&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PRODUCER&apos; has been assigned separator &apos;Default&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD2&apos; has been assigned separator &apos;Default&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD3&apos; has been assigned separator &apos;Default&apos;.
</message>
<message date="1/1/1998" time="">
 Well &apos;PROD4&apos; has been assigned separator &apos;Default&apos;.
</message>
<comment date="1/2/1998" time="31.00000000000000">
          
</comment>
<message date="1/2/1998" time="31.00000000000000">
 Total number of time steps = 1, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/1998" time="59.00000000000000">
          
</comment>
<message date="1/3/1998" time="59.00000000000000">
 Total number of time steps = 2, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/1998" time="90.00000000000000">
          
</comment>
<message date="1/4/1998" time="90.00000000000000">
 Total number of time steps = 3, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/1998" time="120.00000000000000">
          
</comment>
<message date="1/5/1998" time="120.00000000000000">
 Total number of time steps = 4, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/1998" time="151.00000000000000">
          
</comment>
<message date="1/6/1998" time="151.00000000000000">
 Total number of time steps = 5, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/1998" time="181.00000000000000">
          
</comment>
<message date="1/7/1998" time="181.00000000000000">
 Total number of time steps = 6, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/1998" time="212.00000000000000">
          
</comment>
<message date="1/8/1998" time="212.00000000000000">
 Total number of time steps = 7, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/1998" time="243.00000000000000">
          
</comment>
<message date="1/9/1998" time="243.00000000000000">
 Total number of time steps = 8, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/1998" time="273.00000000000000">
          
</comment>
<message date="1/10/1998" time="273.00000000000000">
 Total number of time steps = 9, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/1998" time="304.00000000000000">
          
</comment>
<message date="1/11/1998" time="304.00000000000000">
 Total number of time steps = 10, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/1998" time="334.00000000000000">
          
</comment>
<message date="1/12/1998" time="334.00000000000000">
 Total number of time steps = 11, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/1999" time="365.00000000000000">
          
</comment>
<message date="1/1/1999" time="365.00000000000000">
 Total number of time steps = 12, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/1999" time="396.00000000000000">
          
</comment>
<message date="1/2/1999" time="396.00000000000000">
 Total number of time steps = 13, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/1999" time="424.00000000000000">
          
</comment>
<message date="1/3/1999" time="424.00000000000000">
 Total number of time steps = 14, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/1999" time="455.00000000000000">
          
</comment>
<message date="1/4/1999" time="455.00000000000000">
 Total number of time steps = 15, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/1999" time="485.00000000000000">
          
</comment>
<message date="1/5/1999" time="485.00000000000000">
 Total number of time steps = 16, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/1999" time="516.00000000000000">
          
</comment>
<message date="1/6/1999" time="516.00000000000000">
 Total number of time steps = 17, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/1999" time="546.00000000000000">
          
</comment>
<message date="1/7/1999" time="546.00000000000000">
 Total number of time steps = 18, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/1999" time="577.00000000000000">
          
</comment>
<message date="1/8/1999" time="577.00000000000000">
 Total number of time steps = 19, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/1999" time="608.00000000000000">
          
</comment>
<message date="1/9/1999" time="608.00000000000000">
 Total number of time steps = 20, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/1999" time="638.00000000000000">
          
</comment>
<message date="1/10/1999" time="638.00000000000000">
 Total number of time steps = 21, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/1999" time="669.00000000000000">
          
</comment>
<message date="1/11/1999" time="669.00000000000000">
 Total number of time steps = 22, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/1999" time="699.00000000000000">
          
</comment>
<message date="1/12/1999" time="699.00000000000000">
 Total number of time steps = 23, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2000" time="730.00000000000000">
          
</comment>
<message date="1/1/2000" time="730.00000000000000">
 Total number of time steps = 24, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2000" time="761.00000000000000">
          
</comment>
<message date="1/2/2000" time="761.00000000000000">
 Total number of time steps = 25, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2000" time="790.00000000000000">
          
</comment>
<message date="1/3/2000" time="790.00000000000000">
 Total number of time steps = 26, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2000" time="821.00000000000000">
          
</comment>
<message date="1/4/2000" time="821.00000000000000">
 Total number of time steps = 27, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2000" time="851.00000000000000">
          
</comment>
<message date="1/5/2000" time="851.00000000000000">
 Total number of time steps = 28, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2000" time="882.00000000000000">
          
</comment>
<message date="1/6/2000" time="882.00000000000000">
 Total number of time steps = 29, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2000" time="912.00000000000000">
          
</comment>
<message date="1/7/2000" time="912.00000000000000">
 Total number of time steps = 30, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2000" time="943.00000000000000">
          
</comment>
<message date="1/8/2000" time="943.00000000000000">
 Total number of time steps = 31, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2000" time="974.00000000000000">
          
</comment>
<message date="1/9/2000" time="974.00000000000000">
 Total number of time steps = 32, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2000" time="1004.00000000000000">
          
</comment>
<message date="1/10/2000" time="1004.00000000000000">
 Total number of time steps = 33, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2000" time="1035.00000000000000">
          
</comment>
<message date="1/11/2000" time="1035.00000000000000">
 Total number of time steps = 34, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2000" time="1065.00000000000000">
          
</comment>
<message date="1/12/2000" time="1065.00000000000000">
 Total number of time steps = 35, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2001" time="1096.00000000000000">
          
</comment>
<message date="1/1/2001" time="1096.00000000000000">
 Total number of time steps = 36, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2001" time="1127.00000000000000">
          
</comment>
<message date="1/2/2001" time="1127.00000000000000">
 Total number of time steps = 37, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2001" time="1155.00000000000000">
          
</comment>
<message date="1/3/2001" time="1155.00000000000000">
 Total number of time steps = 38, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2001" time="1186.00000000000000">
          
</comment>
<message date="1/4/2001" time="1186.00000000000000">
 Total number of time steps = 39, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2001" time="1216.00000000000000">
          
</comment>
<message date="1/5/2001" time="1216.00000000000000">
 Total number of time steps = 40, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2001" time="1247.00000000000000">
          
</comment>
<message date="1/6/2001" time="1247.00000000000000">
 Total number of time steps = 41, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2001" time="1277.00000000000000">
          
</comment>
<message date="1/7/2001" time="1277.00000000000000">
 Total number of time steps = 42, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2001" time="1308.00000000000000">
          
</comment>
<message date="1/8/2001" time="1308.00000000000000">
 Total number of time steps = 43, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2001" time="1339.00000000000000">
          
</comment>
<message date="1/9/2001" time="1339.00000000000000">
 Total number of time steps = 44, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2001" time="1369.00000000000000">
          
</comment>
<message date="1/10/2001" time="1369.00000000000000">
 Total number of time steps = 45, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2001" time="1400.00000000000000">
          
</comment>
<message date="1/11/2001" time="1400.00000000000000">
 Total number of time steps = 46, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2001" time="1430.00000000000000">
          
</comment>
<message date="1/12/2001" time="1430.00000000000000">
 Total number of time steps = 47, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2002" time="1461.00000000000000">
          
</comment>
<message date="1/1/2002" time="1461.00000000000000">
 Total number of time steps = 48, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2002" time="1492.00000000000000">
          
</comment>
<message date="1/2/2002" time="1492.00000000000000">
 Total number of time steps = 49, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2002" time="1520.00000000000000">
          
</comment>
<message date="1/3/2002" time="1520.00000000000000">
 Total number of time steps = 50, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2002" time="1551.00000000000000">
          
</comment>
<message date="1/4/2002" time="1551.00000000000000">
 Total number of time steps = 51, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2002" time="1581.00000000000000">
          
</comment>
<message date="1/5/2002" time="1581.00000000000000">
 Total number of time steps = 52, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2002" time="1612.00000000000000">
          
</comment>
<message date="1/6/2002" time="1612.00000000000000">
 Total number of time steps = 53, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2002" time="1642.00000000000000">
          
</comment>
<message date="1/7/2002" time="1642.00000000000000">
 Total number of time steps = 54, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2002" time="1673.00000000000000">
          
</comment>
<message date="1/8/2002" time="1673.00000000000000">
 Total number of time steps = 55, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2002" time="1704.00000000000000">
          
</comment>
<message date="1/9/2002" time="1704.00000000000000">
 Total number of time steps = 56, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2002" time="1734.00000000000000">
          
</comment>
<message date="1/10/2002" time="1734.00000000000000">
 Total number of time steps = 57, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2002" time="1765.00000000000000">
          
</comment>
<message date="1/11/2002" time="1765.00000000000000">
 Total number of time steps = 58, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2002" time="1795.00000000000000">
          
</comment>
<message date="1/12/2002" time="1795.00000000000000">
 Total number of time steps = 59, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2003" time="1826.00000000000000">
          
</comment>
<message date="1/1/2003" time="1826.00000000000000">
 Total number of time steps = 60, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2003" time="1857.00000000000000">
          
</comment>
<message date="1/2/2003" time="1857.00000000000000">
 Total number of time steps = 61, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2003" time="1885.00000000000000">
          
</comment>
<message date="1/3/2003" time="1885.00000000000000">
 Total number of time steps = 62, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2003" time="1916.00000000000000">
          
</comment>
<message date="1/4/2003" time="1916.00000000000000">
 Total number of time steps = 63, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2003" time="1946.00000000000000">
          
</comment>
<message date="1/5/2003" time="1946.00000000000000">
 Total number of time steps = 64, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2003" time="1977.00000000000000">
          
</comment>
<message date="1/6/2003" time="1977.00000000000000">
 Total number of time steps = 65, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2003" time="2007.00000000000000">
          
</comment>
<message date="1/7/2003" time="2007.00000000000000">
 Total number of time steps = 66, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2003" time="2038.00000000000000">
          
</comment>
<message date="1/8/2003" time="2038.00000000000000">
 Total number of time steps = 67, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2003" time="2069.00000000000000">
          
</comment>
<message date="1/9/2003" time="2069.00000000000000">
 Total number of time steps = 68, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2003" time="2099.00000000000000">
          
</comment>
<message date="1/10/2003" time="2099.00000000000000">
 Total number of time steps = 69, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2003" time="2130.00000000000000">
          
</comment>
<message date="1/11/2003" time="2130.00000000000000">
 Total number of time steps = 70, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2003" time="2160.00000000000000">
          
</comment>
<message date="1/12/2003" time="2160.00000000000000">
 Total number of time steps = 71, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2004" time="2191.00000000000000">
          
</comment>
<message date="1/1/2004" time="2191.00000000000000">
 Total number of time steps = 72, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2004" time="2222.00000000000000">
          
</comment>
<message date="1/2/2004" time="2222.00000000000000">
 Total number of time steps = 73, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2004" time="2251.00000000000000">
          
</comment>
<message date="1/3/2004" time="2251.00000000000000">
 Total number of time steps = 74, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2004" time="2282.00000000000000">
          
</comment>
<message date="1/4/2004" time="2282.00000000000000">
 Total number of time steps = 75, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2004" time="2312.00000000000000">
          
</comment>
<message date="1/5/2004" time="2312.00000000000000">
 Total number of time steps = 76, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2004" time="2343.00000000000000">
          
</comment>
<message date="1/6/2004" time="2343.00000000000000">
 Total number of time steps = 77, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2004" time="2373.00000000000000">
          
</comment>
<message date="1/7/2004" time="2373.00000000000000">
 Total number of time steps = 78, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2004" time="2404.00000000000000">
          
</comment>
<message date="1/8/2004" time="2404.00000000000000">
 Total number of time steps = 79, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2004" time="2435.00000000000000">
          
</comment>
<message date="1/9/2004" time="2435.00000000000000">
 Total number of time steps = 80, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2004" time="2465.00000000000000">
          
</comment>
<message date="1/10/2004" time="2465.00000000000000">
 Total number of time steps = 81, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2004" time="2496.00000000000000">
          
</comment>
<message date="1/11/2004" time="2496.00000000000000">
 Total number of time steps = 82, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2004" time="2526.00000000000000">
          
</comment>
<message date="1/12/2004" time="2526.00000000000000">
 Total number of time steps = 83, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2005" time="2557.00000000000000">
          
</comment>
<message date="1/1/2005" time="2557.00000000000000">
 Total number of time steps = 84, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2005" time="2588.00000000000000">
          
</comment>
<message date="1/2/2005" time="2588.00000000000000">
 Total number of time steps = 85, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2005" time="2616.00000000000000">
          
</comment>
<message date="1/3/2005" time="2616.00000000000000">
 Total number of time steps = 86, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2005" time="2647.00000000000000">
          
</comment>
<message date="1/4/2005" time="2647.00000000000000">
 Total number of time steps = 87, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2005" time="2677.00000000000000">
          
</comment>
<message date="1/5/2005" time="2677.00000000000000">
 Total number of time steps = 88, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2005" time="2708.00000000000000">
          
</comment>
<message date="1/6/2005" time="2708.00000000000000">
 Total number of time steps = 89, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2005" time="2738.00000000000000">
          
</comment>
<message date="1/7/2005" time="2738.00000000000000">
 Total number of time steps = 90, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2005" time="2769.00000000000000">
          
</comment>
<message date="1/8/2005" time="2769.00000000000000">
 Total number of time steps = 91, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2005" time="2800.00000000000000">
          
</comment>
<message date="1/9/2005" time="2800.00000000000000">
 Total number of time steps = 92, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2005" time="2830.00000000000000">
          
</comment>
<message date="1/10/2005" time="2830.00000000000000">
 Total number of time steps = 93, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2005" time="2861.00000000000000">
          
</comment>
<message date="1/11/2005" time="2861.00000000000000">
 Total number of time steps = 94, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2005" time="2891.00000000000000">
          
</comment>
<message date="1/12/2005" time="2891.00000000000000">
 Total number of time steps = 95, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2006" time="2922.00000000000000">
          
</comment>
<message date="1/1/2006" time="2922.00000000000000">
 Total number of time steps = 96, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2006" time="2953.00000000000000">
          
</comment>
<message date="1/2/2006" time="2953.00000000000000">
 Total number of time steps = 97, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2006" time="2981.00000000000000">
          
</comment>
<message date="1/3/2006" time="2981.00000000000000">
 Total number of time steps = 98, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2006" time="3012.00000000000000">
          
</comment>
<message date="1/4/2006" time="3012.00000000000000">
 Total number of time steps = 99, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2006" time="3042.00000000000000">
          
</comment>
<message date="1/5/2006" time="3042.00000000000000">
 Total number of time steps = 100, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2006" time="3073.00000000000000">
          
</comment>
<message date="1/6/2006" time="3073.00000000000000">
 Total number of time steps = 101, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2006" time="3103.00000000000000">
          
</comment>
<message date="1/7/2006" time="3103.00000000000000">
 Total number of time steps = 102, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2006" time="3134.00000000000000">
          
</comment>
<message date="1/8/2006" time="3134.00000000000000">
 Total number of time steps = 103, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2006" time="3165.00000000000000">
          
</comment>
<message date="1/9/2006" time="3165.00000000000000">
 Total number of time steps = 104, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2006" time="3195.00000000000000">
          
</comment>
<message date="1/10/2006" time="3195.00000000000000">
 Total number of time steps = 105, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2006" time="3226.00000000000000">
          
</comment>
<message date="1/11/2006" time="3226.00000000000000">
 Total number of time steps = 106, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2006" time="3256.00000000000000">
          
</comment>
<message date="1/12/2006" time="3256.00000000000000">
 Total number of time steps = 107, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2007" time="3287.00000000000000">
          
</comment>
<message date="1/1/2007" time="3287.00000000000000">
 Total number of time steps = 108, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/2/2007" time="3318.00000000000000">
          
</comment>
<message date="1/2/2007" time="3318.00000000000000">
 Total number of time steps = 109, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/3/2007" time="3346.00000000000000">
          
</comment>
<message date="1/3/2007" time="3346.00000000000000">
 Total number of time steps = 110, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/4/2007" time="3377.00000000000000">
          
</comment>
<message date="1/4/2007" time="3377.00000000000000">
 Total number of time steps = 111, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/5/2007" time="3407.00000000000000">
          
</comment>
<message date="1/5/2007" time="3407.00000000000000">
 Total number of time steps = 112, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/6/2007" time="3438.00000000000000">
          
</comment>
<message date="1/6/2007" time="3438.00000000000000">
 Total number of time steps = 113, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/7/2007" time="3468.00000000000000">
          
</comment>
<message date="1/7/2007" time="3468.00000000000000">
 Total number of time steps = 114, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/8/2007" time="3499.00000000000000">
          
</comment>
<message date="1/8/2007" time="3499.00000000000000">
 Total number of time steps = 115, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/9/2007" time="3530.00000000000000">
          
</comment>
<message date="1/9/2007" time="3530.00000000000000">
 Total number of time steps = 116, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/10/2007" time="3560.00000000000000">
          
</comment>
<message date="1/10/2007" time="3560.00000000000000">
 Total number of time steps = 117, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/11/2007" time="3591.00000000000000">
          
</comment>
<message date="1/11/2007" time="3591.00000000000000">
 Total number of time steps = 118, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/12/2007" time="3621.00000000000000">
          
</comment>
<message date="1/12/2007" time="3621.00000000000000">
 Total number of time steps = 119, nonlinear iterations = 0, linear iterations = 0 

</message>
<comment date="1/1/2008" time="3652.00000000000000">
          
</comment>
<message date="1/1/2008" time="3652.00000000000000">
 Total number of time steps = 120, nonlinear iterations = 0, linear iterations = 0 

</message>
<message date="1/1/2008" time="3652.00000000000000">
 Total number of time steps = 120, nonlinear iterations = 0, linear iterations = 0 

</message>
<message date="1/1/2008" time="3652.00000000000000">
 For reports on component CPU time in addition to component elapsed time set Simulation:ProcessInformation &gt; 1.
</message>
<message date="1/1/2008" time="3652.00000000000000">
 For more frequent reports on component CPU and memory set Simulation:ProcessInformation &gt; 2.

</message>
<message date="1/1/2008" time="3652.00000000000000">
 Reports on black-oil fluid model extrapolations can be enabled and controlled using FluidMgr.VerbosityLevel: 
      1 = track total extrapolations during the simulation and show a report for each non-convergent time-step
      2 = report after each time-step
      3 = report for each nonlinear iteration where extrapolations were recorded

</message>
<message date="1/1/2008" time="3652.00000000000000">
 Checked in license feature ix_base 
</message>
<message date="1/1/2008" time="3652.00000000000000">
 Time stepping stats: number of Nosim = 120, total = 120.
</message>
<message date="1/1/1998" time="">
 Checked in license feature ix_fm 
</message>
<message date="1/1/1998" time="">
 Run finished normally.
</message>
</ix>
